development: &DEFAULT
  adapter: postgresql
  encoding: utf8
  database: management_zone_development
  pool: 5
  username: sergiobayona
  password:

test:
  <<: *DEFAULT
  database: management_zone_test

