# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b5bcd615e887d497ec56653dd724d9fe20b68a7ab6f5ceb97eaf61b8e77ed9d417de1ee1d66f92f58fdbca6fb284b11dcc7d9145e1cd5573f56fbdc95a1919f

test:
  secret_key_base: c3be4db3a9e5dafabd2b791210527a0daadd7607c68b5e8948dba2a69abe979427e71fb46b564255c44d9733e7c9fae09e614360937a824ac145876c716309f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
